_target_: src.models.cifar100_module.CIFAR100LitModule
net:
  _target_: src.models.components.net4.Net4
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

compile: false
