_target_: src.models.cifar100_module.CIFAR100LitModule
net:
  _target_: src.models.components.efficientnet.EfficientNet
  model_name: efficientnet_b2
  num_classes: 100
  image_size: 32
  pretrained: false
  freeze_backbone: false
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

compile: false
